@host=localhost:5001

GET http://{{host}}/api/timechimp/customers HTTP/1.1

###

POST http://{{host}}/api/timechimp/customer HTTP/1.1
Content-Type: application/json

{
    "name": "test"
}

###

GET http://{{host}}/api/timechimp/times HTTP/1.1

###

GET http://{{host}}/api/timechimp/contacts HTTP/1.1

###

POST http://{{host}}/api/timechimp/contact HTTP/1.1
Content-Type: application/json

{
    "name": "testing",
    "email": "test@gmail.com"
}

###

PUT http://{{host}}/api/timechimp/contacten HTTP/1.1
Content-Type: application/json

{
    "id": 126289,
    "name": "test",
    "email": "test@gmail.com",
    "useForInvoicing": false,
    "phone": "0123456789",
    "customerIds": [1329003]
}

###

GET http://{{host}}/api/timechimp/mileage HTTP/1.1

###

Get http://{{host}}/api/ets/customerids?dateString=1899-12-30 HTTP/1.1

###

GET http://{{host}}/api/ets/contactids?dateString=1899-12-30 HTTP/1.1

###

GET http://{{host}}/api/ets/projectids?dateString=1899-12-30 HTTP/1.1

###

GET http://{{host}}/api/ets/employeeids?dateString=1899-12-30 HTTP/1.1

###

GET http://{{host}}/api/ets/updateEmployee?employeeid=0006 HTTP/1.1

###

GET http://{{host}}/api/ets/updateProject?projectId=0000001 HTTP/1.1

###

GET http://{{host}}/api/ets/updateCustomer?customerId=000002 HTTP/1.1

###

GET http://{{host}}/api/ets/times HTTP/1.1

###

GET http://{{host}}/api/ets/mileage HTTP/1.1

###

GET http://{{host}}/api/timechimp/mileages HTTP/1.1