namespace Api.Devion.Models;

public class ArticleETS
{
    public string? ART_NR { get; set; }
    public object? ART_LEV1 { get; set; }
    public object? ART_LEV2 { get; set; }
    public object? ART_LEV3 { get; set; }
    public object? ART_LEV4 { get; set; }
    public object? ART_OMS { get; set; }
    public float? ART_AANKP { get; set; }
    public object? ART_VERKP { get; set; }
    public object? ART_INVPR { get; set; }
    public object? ART_BTW { get; set; }
    public object? ART_EENH { get; set; }
    public object? ART_MUTATI { get; set; }
    public object? ART_MINST { get; set; }
    public object? ART_MAXST { get; set; }
    public object? ART_STOCK { get; set; }
    public object? ART_BACKOR { get; set; }
    public object? ART_GERES { get; set; }
    public object? ART_BHOEV { get; set; }
    public object? ART_AANKPV { get; set; }
    public object? ART_MNT { get; set; }
    public object? ART_INFO1 { get; set; }
    public object? ART_INFO2 { get; set; }
    public object? ART_INFO3 { get; set; }
    public object? ART_INFO4 { get; set; }
    public object? ART_INFO5 { get; set; }
    public object? ART_INFO6 { get; set; }
    public object? ART_PR1 { get; set; }
    public object? ART_PR2 { get; set; }
    public object? ART_PR3 { get; set; }
    public object? ART_PR4 { get; set; }
    public object? ART_DAT1 { get; set; }
    public object? ART_DAT2 { get; set; }
    public object? ART_DAT3 { get; set; }
    public object? ART_DAT4 { get; set; }
    public object? ART_AAN1 { get; set; }
    public object? ART_AAN2 { get; set; }
    public object? ART_AAN3 { get; set; }
    public object? ART_AAN4 { get; set; }
    public object? ART_FAM { get; set; }
    public object? ART_ACTIEF { get; set; }
    public object? ART_STOCK2 { get; set; }
    public object? ART_STOCK3 { get; set; }
    public object? ART_STOCK4 { get; set; }
    public object? ART_MAT { get; set; }
    public object? ART_FASE1 { get; set; }
    public object? ART_FASE2 { get; set; }
    public object? ART_BARC { get; set; }
    public object? ART_OLEV { get; set; }
    public object? ART_VERKP2 { get; set; }
    public object? ART_IMP { get; set; }
    public object? ART_MERK { get; set; }
    public object? ART_VELD1 { get; set; }
    public object? ART_VELD2 { get; set; }
    public object? ART_OMSENG { get; set; }
    public object? ART_OMSDUI { get; set; }
    public object? ART_OMSFRA { get; set; }
    public object? ART_VERBTW { get; set; }
    public object? ART_MEMO1 { get; set; }
    public object? ART_NEWSTC { get; set; }
    public object? ART_REMARK { get; set; }
    public object? ART_INVAAN { get; set; }
    public object? ART_WPROC { get; set; }
    public object? ART_WVERK { get; set; }
    public object? ART_LNDCDE { get; set; }
    public object? ART_BARNR { get; set; }
    public object? ART_AFRONDEN { get; set; }
    public object? ART_AFAANTAL { get; set; }
    public string? ART_LEVREF { get; set; }
    public object? ART_INTRASTAT { get; set; }
    public object? ART_PALLET { get; set; }
    public object? ART_CAT { get; set; }
    public object? ART_KORT { get; set; }
    public object? ART_TOEB { get; set; }
    public object? ART_MONT { get; set; }
    public object? ART_TOESL { get; set; }
    public object? ART_MATERIAAL { get; set; }
    public object? ART_INHOUD { get; set; }
    public object? ART_DIAMETER { get; set; }
    public object? ART_LENGTE { get; set; }
    public object? ART_BREEDTE { get; set; }
    public object? ART_WANDDIKTE { get; set; }
    public object? ART_PLAATS { get; set; }
    public object? ART_DRUK { get; set; }
    public object? ART_HOOGTE { get; set; }
    public object? ART_VH { get; set; }
    public object? ART_SOORT { get; set; }
    public object? ART_SGEW { get; set; }
    public object? ART_KGM { get; set; }
    public object? ART_OLDSTOCK { get; set; }
    public object? ART_NR_GRID { get; set; }
    public object? ART_GERESERVEERD { get; set; }
    public object? ART_PORTEFEUILLE { get; set; }
    public object? ART_REK { get; set; }
    public object? ART_GEWICHT { get; set; }
    public object? ART_BESTEL { get; set; }
    public object? ART_SELECT { get; set; }
    public object? ART_BESTELLEV { get; set; }
    public object? ART_IMP_AANK { get; set; }
    public object? ART_RESSTOCK { get; set; }
    public object? ART_VOLUME { get; set; }
    public object? ART_NETTOGEWICHT { get; set; }
    public object? ART_DIAVOET { get; set; }
    public object? ART_DIATOP { get; set; }
    public object? ART_LPH { get; set; }
    public object? ART_LUITNR { get; set; }
    public object? ART_HOEKUITH { get; set; }
    public object? ART_TYPEMAT { get; set; }
    public object? ART_TEKENING { get; set; }
    public object? ART_OPPBEH1 { get; set; }
    public object? ART_OPPBEH2 { get; set; }
    public object? ART_OMSNED2 { get; set; }
    public object? ART_OMSFR2 { get; set; }
    public object? ART_OMSD2 { get; set; }
    public object? ART_AKTIEF { get; set; }
    public object? ART_OMSENG2 { get; set; }
    public object? ART_LEVTERM { get; set; }
    public object? ART_AFM1 { get; set; }
    public object? ART_AFM2 { get; set; }
    public object? ART_AFM3 { get; set; }
    public object? ART_NR2 { get; set; }
    public object? ART_CATEGORIE { get; set; }
    public object? ART_GROEP { get; set; }
    public object? ART_SUBGROEP { get; set; }
    public object? ART_KORTINGSGROEP { get; set; }
    public object? ART_VERPAKEENH { get; set; }
    public object? BESTHOEV { get; set; }
    public object? LEVTERM { get; set; }
    public object? LEVEENH { get; set; }
    public object? GARANTIE { get; set; }
    public object? ART_KOMMISSIE { get; set; }
    public object? ART_STANDAARD { get; set; }
    public object? ART_TIJD_UITV { get; set; }
    public object? ART_TIJD_OPVOLG { get; set; }
    public object? ART_PRIJSWIJZIGING { get; set; }
    public object? ART_GEMP { get; set; }
    public object? ART_OPP_PER_METER { get; set; }
    public object? ART_GEENSTDKORTING { get; set; }
    public object? ART_UPDATE { get; set; }
    public object? ART_CONVERSIEFACTOR_TYPE { get; set; }
    public object? ART_BEREKENINGSWIJZE { get; set; }
    public object? ART_VERPAKT_PER { get; set; }
    public object? ART_CONVERSIEFACTOR { get; set; }
    public object? ART_SUBFAM { get; set; }
    public object? ART_VERK_EENH { get; set; }
    public object? ART_REMARKDUI { get; set; }
    public object? ART_REMARKENG { get; set; }
    public object? ART_REMARKFRA { get; set; }
    public object? ART_FICTIEVE_AANKP { get; set; }
    public object? ART_VRIJ1 { get; set; }
    public object? ART_SEL { get; set; }
    public object? ART_BESTELPROJ { get; set; }
    public object? ART_BESTELSUBPROJ { get; set; }
    public object? ART_VASTEKOST { get; set; }
    public object? ART_SAMENGESTELD { get; set; }
    public object? ART_ONDERLIGGEND { get; set; }
    public object? ART_KLEUR { get; set; }
    public object? ART_ID { get; set; }
    public object? ART_USER { get; set; }
    public object? ART_BESTEL_LEN { get; set; }
    public object? ART_BESTEL_DIK { get; set; }
    public object? ART_BESTEL_HOOG { get; set; }
    public object? ART_BESTELAANKP { get; set; }
    public object? ART_AANTAL { get; set; }
    public object? ART_BACKORDER_KLANT { get; set; }
    public object? ART_BACKORDER_LEVER { get; set; }
    public object? ART_SYSDATUM { get; set; }
    public object? ART_REMARK_INTERN { get; set; }
    public object? ART_REMARK_AANKOOP { get; set; }
    public object? ART_REMARK_AANKOOP_FRA { get; set; }
    public object? ART_REMARK_AANKOOP_ENG { get; set; }
    public object? ART_REMARK_AANKOOP_DUI { get; set; }
    public object? ART_BARCODE_AFGEDRUKT { get; set; }
    public object? ART_FOTO_EXISTS { get; set; }
    public object? ART_WBEDRAG { get; set; }
    public object? ART_AANKP_VERK { get; set; }
    public object? ART_VERKP_VERK { get; set; }
    public object? ART_PROGRESS_RECID { get; set; }
    public object? DATE_CHANGED { get; set; }
    public object? ART_STATUS_BESTELAANVRAAG { get; set; }
    public object? ART_TEKENINGNUMMER { get; set; }
    public object? ART_VERPAKKINGSARTIKEL { get; set; }
    public object? ART_KOPPELING_DERDEN { get; set; }
    public object? ART_GEKOPPELD_STUKNUMMER { get; set; }
    public object? ART_GESCAND_STUKS { get; set; }
    public object? ART_MEEREKENEN_TOTAAL { get; set; }
    public object? ART_NR_UPPER { get; set; }
    public object? ART_DATUM_PRIJSWIJZIGING { get; set; }
    public object? ART_STOCK_STUK { get; set; }
    public object? ART_STOCK_EHV { get; set; }
    public object? ART_UPDATE_KARDEX { get; set; }
    public object? ART_STOCK_OPMERKING { get; set; }
    public object? ART_LAATSTE_AANKOOPDATUM { get; set; }
    public object? ART_BACKORDER_KLANT_STUK { get; set; }
    public object? ART_BACKORDER_LEVER_STUK { get; set; }
    public object? ART_WIJZIGING_CONF { get; set; }
    public object? ART_PRODUCEER { get; set; }
    public object? ART_AANKOOP_PER { get; set; }
    public object? ART_BESTELARTIKEL { get; set; }
    public object? ART_HYPERLINK { get; set; }
    public object? FIRST_USER { get; set; }
    public object? LAST_USER { get; set; }
    public object? CREATION { get; set; }
    public object? ART_SUBFAMILIE_DETAIL_ID { get; set; }
    public object? ART_OMS_UPPER { get; set; }
    public object? ART_SOORT_OMS { get; set; }
    public object? ART_ARTIKELGROEP_ID { get; set; }
    public object? ART_LOTNUMMER { get; set; }
    public object? ART_MINSTOCK_IN { get; set; }
    public object? ART_MAXSTOCK_IN { get; set; }
    public object? ART_ADMIN2MOBILE { get; set; }
    public object? ART_AANTAL_IN_PRODUCTIE { get; set; }
    public object? ART_FICTIEVE_STOCK { get; set; }
    public object? ART_PROMOPRIJS { get; set; }
    public object? ART_PROMO_DATVAN { get; set; }
    public object? ART_PROMO_DATTOT { get; set; }
    public object? ART_CERTIFICAAT { get; set; }
    public object? ART_PREFAB_ELEMENT { get; set; }
    public object? ART_SERIENUMMER { get; set; }
    public object? ART_MERK_ID { get; set; }
    public object? ART_KEUZELIJST_STOCK_ID { get; set; }
    public object? ART_OPMAAK { get; set; }
    public object? ART_CAR_STOCK { get; set; }
    public object? ART_PRIJSAANVRAAG { get; set; }
    public object? ART_SOM_PRIJSAANVRAAG { get; set; }
    public object? ART_LEVERTERMIJN_DAGEN { get; set; }
    public object? ART_LEVERTERMIJN_MAN_AANGEPAST { get; set; }
    public object? ART_VAN_WORKABOUT { get; set; }
    public object? ART_LAATSTE_VERKOOPDATUM { get; set; }
    public object? ART_SAPA_ID { get; set; }
    public object? ART_MINSTOCK_STUKS { get; set; }
    public object? ART_MAXSTOCK_STUKS { get; set; }
    public object? ART_VELD3 { get; set; }
    public object? ART_WEBSHOP { get; set; }
    public object? ART_REMARK_PLAIN_TEXT { get; set; }

}

public class ArticleWeb
{
    public ArticleWeb() { }

    public ArticleWeb(Item articleCebeo)
    {
        Reference = articleCebeo.Material?.Reference;
        Description = articleCebeo.Material?.Description;
        Brand = articleCebeo.Material?.BrandName;
        UnitOfMeasure = articleCebeo.UnitOfMeasure;
        SalesPackQuantity = articleCebeo.SalesPackQuantity;
        NettoPrice = float.Parse(articleCebeo.UnitPrice?.NetPrice ?? "");
        TarifPrice = float.Parse(articleCebeo.UnitPrice?.TarifPrice ?? "");
        URL = $"https://www.cebeo.be/catalog/nl-be/products/{Brand}-{string.Join('-', Regex.Replace(Description ?? throw new Exception("Article form Cebeo has no description"), "[^0-9A-Za-z _-]", "").Split(' ').Where(x => x != "").Select(x => x.Trim()))}-{articleCebeo.Material?.SupplierItemID ?? throw new Exception("Article form Cebeo has no articleNumber")}".ToLower();
    }

    public string? Reference { get; set; }
    public string? Description { get; set; }
    public string? Brand { get; set; }
    public string? UnitOfMeasure { get; set; }
    public int? SalesPackQuantity { get; set; }
    public float? NettoPrice { get; set; }
    public float? TarifPrice { get; set; }
    public string? URL { get; }
}