namespace Api.Devion.Models;

public class PurchaseOrderHeaderETS
{
    public char? FH_CODE { get; set; }
    public char? FH_OLDCODE { get; set; }
    public object? FH_AFD { get; set; }
    public string FH_BONNR { get; set; }
    public object? FH_FAKNR { get; set; }
    public object? FH_BHLINK { get; set; }
    public object? FH_KLNR { get; set; }
    public object? FH_AUTO { get; set; }
    public object? FH_KILOM { get; set; }
    public object? FH_BVW { get; set; }
    public object? FH_VZW { get; set; }
    public object? FH_AGT { get; set; }
    public object? FH_MEDE { get; set; }
    public object? FH_UITV { get; set; }
    public object? FH_CRDAT { get; set; }
    public object? FH_AFDDAT { get; set; }
    public object? FH_VDAT { get; set; }
    public object? FH_BONDAT { get; set; }
    public object? FH_FAKDAT { get; set; }
    public object? FH_KORT { get; set; }
    public object? FH_VOORS { get; set; }
    public object? FH_WBET { get; set; }
    public object? FH_SEL { get; set; }
    public object? FH_LEVNM { get; set; }
    public object? FH_LEVSTR { get; set; }
    public object? FH_LEVPST { get; set; }
    public object? FH_LEVSTD { get; set; }
    public object? FH_LEVLND { get; set; }
    public object? FH_TEKST { get; set; }
    public object? FH_DETAIL { get; set; }
    public object? FH_BTWEX { get; set; }
    public object? FH_TEKSTV { get; set; }
    public object? FH_REF1 { get; set; }
    public object? FH_REF2 { get; set; }
    public object? FH_REF3 { get; set; }
    public object? FH_SLOT { get; set; }
    public object? FH_VOOR { get; set; }
    public object? FH_TOTPR { get; set; }
    public object? FH_CONTP { get; set; }
    public object? FH_STATUS { get; set; }
    public object? FH_DATAFH { get; set; }
    public object? FH_GESTORT { get; set; }
    public object? FH_COMM { get; set; }
    public object? FH_UREN { get; set; }
    public object? FH_KM { get; set; }
    public object? FH_KMPR { get; set; }
    public object? FH_WCOEF { get; set; }
    public object? FH_MAN { get; set; }
    public object? FH_PERS { get; set; }
    public object? FH_PLOEGBS { get; set; }
    public object? FH_PROJ { get; set; }
    public object? FH_VORD { get; set; }
    public object? FH_EXT1 { get; set; }
    public object? FH_EXT2 { get; set; }
    public object? FH_EXT3 { get; set; }
    public object? FH_DEBLINK { get; set; }
    public object? FH_BV { get; set; }
    public string? FH_UNIEK { get; set; }
    public object? FH_TEKST2 { get; set; }
    public object? FH_AFGEH { get; set; }
    public object? FH_PROSPECT { get; set; }
    public object? FH_PROSPECTNR { get; set; }
    public object? FH_UURPR { get; set; }
    public object? FH_MNT { get; set; }
    public object? FH_KOERS { get; set; }
    public object? FH_LEVADRES { get; set; }
    public object? FH_AFGEWERKT { get; set; }
    public object? FH_FACTUREREN { get; set; }
    public object? FH_CONTAN { get; set; }
    public object? FH_METPRIJS { get; set; }
    public object? FH_METTOTAAL { get; set; }
    public object? FH_AP1 { get; set; }
    public object? FH_AP2 { get; set; }
    public object? FH_AP3 { get; set; }
    public object? FH_AP4 { get; set; }
    public object? FH_EENHEID { get; set; }
    public object? FH_AFMETING { get; set; }
    public object? FH_WEEKLEV { get; set; }
    public object? FH_LEVTAV { get; set; }
    public object? FH_AUTOV { get; set; }
    public object? FH_PLAAT { get; set; }
    public object? VALGOEDEREN { get; set; }
    public object? FH_INTRASTAT { get; set; }
    public object? VALGOEDERENBON { get; set; }
    public object? FH_TRANSPORTEUR { get; set; }
    public object? FH_TECHNIEKER { get; set; }
    public object? FH_AANTALKM { get; set; }
    public object? FH_VERTREKFIRMA { get; set; }
    public object? FH_AANKOMSTKLANT { get; set; }
    public object? FH_AANKOMSTKLANT2 { get; set; }
    public object? FH_VERTREKKLANT { get; set; }
    public object? FH_VERTREKKLANT2 { get; set; }
    public object? FH_AANKOMSTFIRMA { get; set; }
    public object? FH_AANKOMSTFIRMA2 { get; set; }
    public object? FH_URENOPDEBAAN { get; set; }
    public object? FH_URENBIJDEKLANT { get; set; }
    public object? FH_TOTAALUREN { get; set; }
    public object? FH_KORTING { get; set; }
    public object? FH_LEVSTR2 { get; set; }
    public object? FH_REFERENTIE { get; set; }
    public object? OPFACTUUR { get; set; }
    public object? BACKORDER { get; set; }
    public object? REEDSGELEVERD { get; set; }
    public object? OMZETBON { get; set; }
    public object? SALDOBON { get; set; }
    public object? FH_2D { get; set; }
    public object? FH_MINPR { get; set; }
    public object? FH_INTRA2 { get; set; }
    public object? FH_STR3 { get; set; }
    public object? FH_KORTKLANT { get; set; }
    public object? PROJECTOMSCHRIJVING { get; set; }
    public object? KL_WPL { get; set; }
    public object? KL_TEL { get; set; }
    public object? KL_FAX { get; set; }
    public object? KL_AFD { get; set; }
    public object? LV_WPL { get; set; }
    public object? LV_AFD { get; set; }
    public object? FH_CODEOFF { get; set; }
    public object? FH_KLBOE { get; set; }
    public object? FH_INFO { get; set; }
    public object? FH_TAV { get; set; }
    public object? FH_RVS { get; set; }
    public object? FH_STAAL { get; set; }
    public object? FH_ZINCOR { get; set; }
    public object? FH_COLIS { get; set; }
    public object? FH_GEWICHT { get; set; }
    public object? FH_ALU { get; set; }
    public object? FH_TRANSTYPE { get; set; }
    public object? FH_VERPAKKING { get; set; }
    public object? FH_FOLIE { get; set; }
    public object? FH_KARTON { get; set; }
    public object? FH_OPZET { get; set; }
    public object? FH_PALET1 { get; set; }
    public object? FH_PALET2 { get; set; }
    public object? FH_PALET3 { get; set; }
    public object? FH_EUROPALET { get; set; }
    public object? FH_CONTROLE { get; set; }
    public object? FH_TAVEMAIL { get; set; }
    public object? FH_TAVFAX { get; set; }
    public object? FH_PNID { get; set; }
    public object? FH_PLAATSING { get; set; }
    public object? FH_WEDERVERKOPER { get; set; }
    public object? FH_VERHUUR { get; set; }
    public object? FH_VERHUUREVENVANDAT { get; set; }
    public object? FH_VERHUUREVENTOTDAT { get; set; }
    public object? FH_VERHUURBLOKVANDAT { get; set; }
    public object? FH_VERHUURBLOKTOTDAT { get; set; }
    public object? FH_VERHUURPERIODE { get; set; }
    public object? FH_OLDBONNR { get; set; }
    public object? FH_CONTRACTNR { get; set; }
    public object? FH_CONTRACTDATUM { get; set; }
    public object? FH_UITVOERINGDDATUM { get; set; }
    public object? FH_GELDIGHEIDSDATUM { get; set; }
    public object? FH_ORIDOC { get; set; }
    public object? FH_SUBPROJ { get; set; }
    public object? FH_KLONDNR { get; set; }
    public object? FH_DOCPATH { get; set; }
    public object? FH_OVV_EXCEL { get; set; }
    public object? FH_LEVLAND { get; set; }
    public object? FH_AANSPREKING { get; set; }
    public object? FH_CONTACTPERSOON { get; set; }
    public object? FH_LEVPLAATS { get; set; }
    public object? FH_ID { get; set; }
    public object? FH_TAVTEL { get; set; }
    public object? FH_RUDPXDATUM { get; set; }
    public object? FH_KLNR2 { get; set; }
    public object? FH_DOORGESTUURD_RUDPX { get; set; }
    public object? FH_BTW_MVH { get; set; }
    public object? FH_TAAL { get; set; }
    public object? FH_CARPASS_OK { get; set; }
    public object? FH_AFGEDRUKT { get; set; }
    public object? FH_KLNR3 { get; set; }
    public object? FH_AANVRAGER { get; set; }
    public object? FH_AANVRAAG_OF_OFFERTE { get; set; }
    public object? FH_DATUM_AANVRAAG { get; set; }
    public object? FH_CATEGORIE_ID { get; set; }
    public object? FH_TAV_ID { get; set; }
    public object? FH_OPGESTUURD_PER { get; set; }
    public object? FH_OPGESTUURD_DATUM { get; set; }
    public object? FH_TAVAFD { get; set; }
    public object? FH_DATUM_ONDERHOUD { get; set; }
    public object? FH_DATUM_LEVERING { get; set; }
    public object? FH_AANBESTEDING_UITVOERING { get; set; }
    public object? FH_AANBESTEDING_UITVOERING_OMS { get; set; }
    public object? FH_DATUM_GEWENST { get; set; }
    public object? FH_DOSSIERNUMMER { get; set; }
    public object? FH_OPMERKINGEN { get; set; }
    public object? FH_SOM_BTW_EXCL { get; set; }
    public object? FH_AANVRAAG_OF_OFFERTE_OMS { get; set; }
    public object? FH_SYSDATUM { get; set; }
    public object? FH_LAST_USER { get; set; }
    public object? FH_DATUM_WIJZIGING_STATUS { get; set; }
    public object? FH_KLEUR_ID { get; set; }
    public object? FH_SERIE_ID { get; set; }
    public object? FH_INTERVENTIE_ID { get; set; }
    public object? FH_AANVRAGER_OMS { get; set; }
    public object? FH_BUSINESS_UNIT_ID { get; set; }
    public object? FH_FAKTUUR_OPENSTAAND_SALDO { get; set; }
    public object? FH_DOORSTUREN_TYPE { get; set; }
    public object? FH_LEVMEMO { get; set; }
    public object? FH_LAATSTE_RAPPEL_ID { get; set; }
    public object? FH_SOM_BTW_EXCL_2 { get; set; }
    public object? FH_SOM_BTW_INCL { get; set; }
    public object? FH_INFO_DEBITEUR { get; set; }
    public object? FH_BEDRAG_CONTAN { get; set; }
    public object? FH_DATUM_LAATSTE_RAPPEL { get; set; }
    public object? FH_DAGBOEK { get; set; }
    public object? FH_ONTVANGST_REEDS_GESCAND { get; set; }
    public object? FH_VRIJ_VELD { get; set; }
    public object? FH_BTW_CODE_ID { get; set; }
    public object? FH_ARCHITECTENKORTING { get; set; }
    public object? FH_FTP_UPLOAD { get; set; }
    public object? FH_BASISVOERTUIG { get; set; }
    public object? FH_AANTAL { get; set; }
    public object? FH_CHASSIS { get; set; }
    public object? FH_GOEDGEKEURD { get; set; }
    public object? FH_TAVGSM { get; set; }
    public object? FH_CONTACTPERSOON_VOORNAAM { get; set; }
    public object? FH_RENDEMENT { get; set; }
    public object? FH_RENDEMENT_COLOR { get; set; }
    public object? FH_VANPRO { get; set; }
    public object? FH_FIRST_USER { get; set; }
    public object? FH_CREATION { get; set; }
    public object? FH_LEVERDATUM { get; set; }
    public object? FH_CONTACT_FULL { get; set; }
    public object? FH_GEMAILD { get; set; }
    public object? FH_ATTEST_VERSTUURD { get; set; }
    public object? FH_ATTEST_ONTVANGEN { get; set; }
    public object? FH_DATUM_OPEISBAARHEID_BTW { get; set; }
    public object? FH_DOORGESTUURD_PROLOGIC { get; set; }
    public object? FH_FTP_FEEDBACK { get; set; }
    public object? FH_FAKTUUR_OPENSTAAND_INGELEZEN { get; set; }
    public object? FH_ISO_ID { get; set; }
    public object? FH_ISD_ID { get; set; }
    public object? FH_NABEHANDELING { get; set; }
    public object? FH_INCOTERM_ID { get; set; }
    public object? FH_RITNUMMER_HEEN { get; set; }
    public object? FH_RITNUMMER_TERUG { get; set; }
    public object? FH_MEMO { get; set; }
    public object? FH_FACTORING_EXPORT { get; set; }
    public object? LV_STR { get; set; }
    public object? KL_STR { get; set; }
    public object? FH_WEBSHOP { get; set; }
    public object? KL_TAV { get; set; }
    public object? KL_OPV { get; set; }
    public object? KL_NAM { get; set; }
    public object? FH_VRIJ_VELD_1 { get; set; }
    public object? FH_VRIJ_VELD_2 { get; set; }
    public object? FH_VRIJ_VELD_3 { get; set; }
    public object? FH_VRIJ_VELD_4 { get; set; }
    public object? FH_VRIJ_VELD_5 { get; set; }
    public object? FH_CAR_STOCK_ID { get; set; }
    public object? FH_SUBCONTRACT_HOLDIN { get; set; }
    public object? FH_HANDTEKENING { get; set; }
    public object? FH_WINSTBEDRAG { get; set; }
    public object? FH_WINSTPERCENTAGE { get; set; }
    public object? FH_AFGEMELD { get; set; }
    public object? LV_TEL { get; set; }
    public object? LV_FAX { get; set; }
    public object? LV_NAM { get; set; }
    public object? FH_OPVOLGING { get; set; }
    public object? FH_SETTLENUMBER { get; set; }
    public object? FH_SEL_TOURLIJST { get; set; }
    public object? FH_VOLGORDE { get; set; }
    public object? FH_LOCATIE { get; set; }
    public object? FH_OGM { get; set; }
    public object? FH_BEVESTIGD { get; set; }
    public object? FH_STUKNUMMER_MAGAZIJN_ID { get; set; }
    public object? FH_STUKNUMMER_MAGAZIJN_OMS { get; set; }
    public object? FH_LEVTEL { get; set; }
    public object? FH_DOC_VRIJ_VELD1 { get; set; }
    public object? FH_DOC_VRIJ_VELD2 { get; set; }
    public object? FH_DOC_VRIJ_VELD3 { get; set; }
    public object? FH_DOC_VRIJ_VELD4 { get; set; }
    public object? FH_DOC_VRIJ_VELD5 { get; set; }
    public object? FH_DOC_VRIJ_VELD6 { get; set; }
    public object? FH_DOC_VRIJ_VELD7 { get; set; }
    public object? FH_DOC_VRIJ_VELD8 { get; set; }
    public object? FH_DOC_VRIJ_VELD9 { get; set; }
    public object? FH_DOC_VRIJ_VELD10 { get; set; }
    public object? FH_DOC_VRIJ_VELD1_OMS { get; set; }
    public object? FH_DOC_VRIJ_VELD2_OMS { get; set; }
    public object? FH_DOC_VRIJ_VELD3_OMS { get; set; }
    public object? FH_DOC_VRIJ_VELD4_OMS { get; set; }
    public object? FH_DOC_VRIJ_VELD5_OMS { get; set; }
    public object? FH_DOC_VRIJ_VELD6_OMS { get; set; }
    public object? FH_DOC_VRIJ_VELD7_OMS { get; set; }
    public object? FH_DOC_VRIJ_VELD8_OMS { get; set; }
    public object? FH_DOC_VRIJ_VELD9_OMS { get; set; }
    public object? FH_DOC_VRIJ_VELD10_OMS { get; set; }
    public object? FH_RAPPEL_VERSTUREN { get; set; }
    public object? FH_ORDER_STATUS_ID { get; set; }
    public object? FH_ORDER_STATUS_WIJZIGING { get; set; }
}

public class PurchaseOrderDetailETS
{
    public char? FD_CODE { get; set; }
    public char? FD_OLDCODE { get; set; }
    public string FD_BONNR { get; set; }
    public object? FD_FAKNR { get; set; }
    public object? FD_KLNR { get; set; }
    public object? FD_LYNNR { get; set; }
    public object? FD_ARTNR { get; set; }
    public object? FD_ARTLEV { get; set; }
    public object? FD_OMS { get; set; }
    public object? FD_EENH { get; set; }
    public object? FD_VERP { get; set; }
    public object? FD_HOEV { get; set; }
    public object? FD_HVST { get; set; }
    public object? FD_BEDRAG { get; set; }
    public object? FD_BTW { get; set; }
    public object? FD_MUTATIE { get; set; }
    public object? FD_BEST { get; set; }
    public object? FD_FACTOR { get; set; }
    public object? FD_AANVR { get; set; }
    public object? FD_RNC { get; set; }
    public object? FD_MEERPR { get; set; }
    public object? FD_INVUL { get; set; }
    public object? FD_VTOT { get; set; }
    public object? FD_VAR { get; set; }
    public object? FD_WCOEF { get; set; }
    public object? FD_MAT { get; set; }
    public object? FD_FASE1 { get; set; }
    public object? FD_FASE2 { get; set; }
    public object? FD_PROJ { get; set; }
    public object? FD_VORD { get; set; }
    public object? FD_PROC { get; set; }
    public object? FD_OFFBEDR { get; set; }
    public object? FD_VAST { get; set; }
    public object? FD_THOEV { get; set; }
    public string? FD_UNIEK { get; set; }
    public object? FD_SUBT { get; set; }
    public object? FD_PRTOT { get; set; }
    public object? FD_BACKORDER { get; set; }
    public object? FD_GEFAC { get; set; }
    public object? FD_PROCVOORS { get; set; }
    public object? FD_RGELEV { get; set; }
    public object? FD_REFBON { get; set; }
    public object? FD_TELLER { get; set; }
    public object? FD_VPINCL { get; set; }
    public object? FD_KORT { get; set; }
    public object? FD_BTWINCL { get; set; }
    public object? FD_INGAVEPRIJS { get; set; }
    public object? FD_PRIJS1 { get; set; }
    public object? FD_PRIJS2 { get; set; }
    public object? FD_PRIJS3 { get; set; }
    public object? FD_PRIJS4 { get; set; }
    public object? FD_BTWPCT { get; set; }
    public object? FD_TRANSPORT { get; set; }
    public object? FD_INTRASTAT { get; set; }
    public object? FD_GROEP { get; set; }
    public object? FD_MATPR { get; set; }
    public object? FD_TOEPR { get; set; }
    public object? FD_MONT { get; set; }
    public object? FD_INTRA2 { get; set; }
    public object? FD_AUTO { get; set; }
    public object? FD_TERUG { get; set; }
    public object? FD_LTSTBEDRAG { get; set; }
    public object? FD_AANKP { get; set; }
    public object? FD_TOTAKP { get; set; }
    public object? FD_INKOOPORDER { get; set; }
    public object? FD_PNID { get; set; }
    public object? FD_FAKDAT { get; set; }
    public object? FD_BONDAT { get; set; }
    public object? FAKMAAND { get; set; }
    public object? FAKJAAR { get; set; }
    public object? FD_STUKNR { get; set; }
    public object? FD_LTSTHOEV { get; set; }
    public object? EUROTOTAAL { get; set; }
    public object? FD_PROCENT { get; set; }
    public object? FD_LEVEENH { get; set; }
    public object? FD_VERHUUR { get; set; }
    public object? FD_VERHUUROK { get; set; }
    public object? FD_OMS2 { get; set; }
    public object? FD_MCEENH { get; set; }
    public object? FD_TYPE { get; set; }
    public object? FD_SOORT { get; set; }
    public object? FD_VERHUURAANTAL { get; set; }
    public object? FD_EENH_TIJD_UITV { get; set; }
    public object? FD_EENH_TIJD_OPV { get; set; }
    public object? FD_TOT_MANUREN_UITV { get; set; }
    public object? FD_TOT_MANUREN_OPV { get; set; }
    public object? FD_EHP_UURPRIJS { get; set; }
    public object? FD_EHP_PERCENT { get; set; }
    public object? FD_EHP_TOT_MANUREN_UITV { get; set; }
    public object? FD_EHP_TOT_MANUREN_OPV { get; set; }
    public object? FD_DEFAULT_UURPRIJS { get; set; }
    public object? FD_DEFAULT_PERCENT { get; set; }
    public object? FD_AANTAL { get; set; }
    public object? FD_HOOG { get; set; }
    public object? FD_LEN { get; set; }
    public object? FD_DIK { get; set; }
    public object? FD_SGEW { get; set; }
    public object? FD_EHP_MATERIAAL { get; set; }
    public object? FD_SUBPROJ { get; set; }
    public object? FD_CATPRIJS { get; set; }
    public object? FD_ARTKORT { get; set; }
    public object? FD_NETPRIJS { get; set; }
    public object? FD_TOT_MATERIAAL { get; set; }
    public object? FD_EHP_PERCENT_MATERIAAL { get; set; }
    public object? FD_EHP_TOT_MATERIAAL { get; set; }
    public object? FD_TOTAAL { get; set; }
    public object? FD_OMS2ART { get; set; }
    public object? FD_CONVERSIEFACTOR_TYPE { get; set; }
    public object? FD_VERK_EENH { get; set; }
    public object? FD_BEREKENINGSWIJZE { get; set; }
    public object? FD_VERPAKT_PER { get; set; }
    public object? FD_KGM { get; set; }
    public object? FD_CONVERSIEFACTOR { get; set; }
    public object? FD_GEWICHT { get; set; }
    public object? FD_LTSTDATUM { get; set; }
    public object? FD_PRIJSAANVRAAG { get; set; }
    public object? FD_INTRAGEWICHT { get; set; }
    public object? FD_STUKSHVST { get; set; }
    public object? FD_MEMO { get; set; }
    public object? ARTOMS { get; set; }
    public object? FD_AGT { get; set; }
    public object? FD_PROCENTMATERIAAL { get; set; }
    public object? FD_REGDATUM { get; set; }
    public object? FD_LINKTELLER { get; set; }
    public object? FD_MANUEEL_AANGEPAST { get; set; }
    public object? FD_LIJNTOT { get; set; }
    public object? FD_DATUM_BELOOFD { get; set; }
    public object? FD_AANTAL_COLIS { get; set; }
    public object? FD_AANTAL_AF { get; set; }
    public object? FD_LEVDATUM { get; set; }
    public object? FD_LEN_NOTNULL { get; set; }
    public object? FD_DIK_NOTNULL { get; set; }
    public object? FD_HOOG_NOTNULL { get; set; }
    public object? FD_AANTAL_NOTNULL { get; set; }
    public object? FD_PLANNR { get; set; }
    public object? FD_OPP { get; set; }
    public object? FD_GEW { get; set; }
    public object? FD_MEMO2 { get; set; }
    public object? FD_ORDER_ID { get; set; }
    public object? FD_KLEUR_ID { get; set; }
    public object? FD_ARTIKELPRIJS_AANPASSEN { get; set; }
    public object? FD_TEBESTELLEN { get; set; }
    public object? FD_SELECT { get; set; }
    public object? FD_INBESTELLIJST { get; set; }
    public object? FD_PROJECT_BESTAANVR_ID { get; set; }
    public object? FD_LAADDATUM { get; set; }
    public object? FD_HUIDIGE_STOCK { get; set; }
    public object? FD_STOCK_UPDATEN { get; set; }
    public object? FD_LEVERING_VERWACHT { get; set; }
    public object? FD_INT_PRESTATIE_ID { get; set; }
    public object? FD_INT_DETAIL_ID { get; set; }
    public object? FD_REK { get; set; }
    public object? FD_INTERVENTIE_ID { get; set; }
    public object? FD_TEKENINGNUMMER { get; set; }
    public object? FD_SYSDATUM { get; set; }
    public object? FD_HVST_PROCENT { get; set; }
    public object? FD_LIJN_TYPE { get; set; }
    public object? FD_VCL_ID { get; set; }
    public object? FD_RUD_SOORT { get; set; }
    public object? FD_HERBEREKEN_LBH { get; set; }
    public object? FD_TEKENING { get; set; }
    public object? FD_SERIE { get; set; }
    public object? FD_ISONDERLIGGEND { get; set; }
    public object? FD_INTERVENTIE_UREN_ID { get; set; }
    public object? FD_INTERVENTIE_MATERIALEN_ID { get; set; }
    public object? FD_INTERVENTIE_DERDEN_ID { get; set; }
    public object? FD_POSNR { get; set; }
    public object? FD_BLOK_ID { get; set; }
    public object? FD_VOLGNUMMER_SAPA { get; set; }
    public object? FD_LAST_USER { get; set; }
    public object? FD_FIRST_USER { get; set; }
    public object? FD_CREATION { get; set; }
    public object? FD_MUTATIEOMS { get; set; }
    public object? FD_AGTOMS { get; set; }
    public object? FD_PICTURE_CLASS { get; set; }
    public object? FD_DOORSTUREN_ORDERLIJN { get; set; }
    public object? FD_DOORGESTUURD_ORDERLIJN { get; set; }
    public object? FD_AFREKENING_PROJ { get; set; }
    public object? FD_AANPASSEN_PRIJS_STUKNR { get; set; }
    public object? FD_STD_GEWICHT { get; set; }
    public object? FD_LOTNUMMER { get; set; }
    public object? FD_VERVALDATUM { get; set; }
    public object? FD_DOORSTUREN_ORDERLIJN_KLAAR { get; set; }
    public object? FD_OPMAAK { get; set; }
    public object? KLANTNAAM { get; set; }
    public object? REF2 { get; set; }
    public object? FD_BLO_SELECT { get; set; }
    public object? FD_BLO_BESTEL { get; set; }
    public object? FD_BLO_ORDER { get; set; }
    public object? FD_BLO_BESTELBON { get; set; }
    public object? FD_BLO_LEV { get; set; }
    public object? FD_BLO_HOEV { get; set; }
    public object? FD_BLO_AANTAL { get; set; }
    public object? FD_MAT_ID { get; set; }
    public object? FD_GARANTIE { get; set; }
    public object? FD_ARTIKEL_CERTIFICAAT_ID { get; set; }
    public object? FD_SERIENUMMER { get; set; }
    public object? FD_INSERT_VIA_AFREKENING_PROJ { get; set; }
    public object? FD_INSERT_VIA_OVERNAME_ORDER { get; set; }
    public object? FD_INSERT_VIA_OVERNAME_LEVBON { get; set; }
    public object? FD_INFO { get; set; }
    public object? FD_ARTIKEL_LOCATIE_ID { get; set; }
    public object? FD_KLANTREFERENTIE { get; set; }
    public object? FD_VELD1 { get; set; }
    public object? FD_CAR_STOCK_ID { get; set; }
    public object? FD_WINSTPERCENTAGE { get; set; }
    public object? FD_AUTONUMMER { get; set; }
    public object? FD_KLEUR_BINNEN_ID { get; set; }
    public object? FD_KLEUR_BUITEN_ID { get; set; }
    public object? FD_HELPDESK_MATERIAAL_ID { get; set; }
    public object? FD_APLUSW_POSITIE { get; set; }
    public object? FD_APLUSW_OPPERVLAKTE { get; set; }
    public object? FD_APLUSW_PRIJS_PER_OPP { get; set; }
    public object? FD_APLUSW_EENHEID_NETTO { get; set; }
    public object? FD_INTERN { get; set; }
    public object? REF1 { get; set; }
    public object? REF3 { get; set; }
    public object? FD_LOCATIE { get; set; }
    public object? FD_STUKNUMMER_MAGAZIJN_ID { get; set; }
    public object? FD_STUKNUMMER_MAGAZIJN_OMS { get; set; }
    public object? FD_LIJN_KLEUR { get; set; }
    public object? FD_POSITIE { get; set; }
    public object? FD_VRIJ_VELD1_NUMERIEK { get; set; }
    public object? FD_VRIJ_VELD2_NUMERIEK { get; set; }
}
